# Exported from Render on 2025-12-07T14:49:56Z
version: "1"
services:
- type: web
  name: playground-api
  runtime: docker
  repo: https://github.com/thebaggieboy/playground-backend
  plan: free
  envVars:
  - key: REDIS_URL
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: EMAIL_HOST_PASSWORD
    sync: false
  - key: EMAIL_HOST_USER
    sync: false
  - key: EMAIL_USE_TLS
    sync: false
  - key: EMAIL_PORT
    sync: false
  - key: EMAIL_HOST
    sync: false
  - key: DATABASE_SSL_REQUIRE
    sync: false
  - key: DATABASE_CONN_MAX_AGE
    sync: false
  - key: DEBUG
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
